# Generated by Django 2.1.2 on 2018-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Actor', '0001_initial'),
        ('Company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget', models.IntegerField(default=0)),
                ('name', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('language', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('overview', models.TextField(default=None)),
                ('country', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('date', models.DateField(default=None)),
                ('revenue', models.BigIntegerField(default=0)),
                ('runtime', models.IntegerField(default=0)),
                ('tagline', models.TextField(default=None)),
                ('actors', models.ManyToManyField(to='Actor.Actor')),
                ('companies', models.ManyToManyField(to='Company.Company')),
            ],
            options={
                'verbose_name': 'Film',
                'verbose_name_plural': 'Films',
            },
        ),
    ]
