# Generated by Django 2.1.2 on 2018-11-25 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Genre', '0001_initial'),
        ('Film', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='genres',
            field=models.ManyToManyField(to='Genre.Genre'),
        ),
    ]
