# Generated by Django 2.1.2 on 2018-12-02 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Actor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='actor',
            name='birthday',
        ),
        migrations.AddField(
            model_name='actor',
            name='image',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
