# Generated by Django 2.1.2 on 2018-12-02 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Genre', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='image',
            field=models.TextField(default=None),
        ),
    ]
